### ISSUE TITLE
Padrón de Taxis - Sinaloa

### ISSUE THREAD

**Issue by edgargutgzz** [EdgarGtz/taxi-padron#12]

**Comment by edgargutgzz** [comment]
No seas huevón!

**Comment by ricalanis** [comment]
Listo con #29 , ¡Asigname otro prroooo!

**Comment by israelzuniga** [comment]
@ricalanis Tres meses para acabar un CSV. Te pasas de rosca... 😹

**Comment by ricalanis** [comment]
Jijijiji esque el pandas no cargaba @israelzuniga
