### ISSUE TITLE
Padrón de Taxis - Colima

### ISSUE THREAD

**Issue by edgargutgzz** [EdgarGtz/taxi-padron#25]

**Comment by israelzuniga** [comment]
Al cargar el CSV, no se hace parsing de algunas líneas (46). Dejo su número de posición a continuación:



 1558
 1559
 1560
 1561
 1562
 1563
 1564
 1565
 1566
 1567
 1568
 1569
 1570
 1571
 1572
 1573
 1574
 1575
 1576
 1577
 1578
 1579
 1580
 3006
 3007
 3008
 3009
 3010
 3011
 3012
 3013
 3014
 3015
 3016
 3017
 3018
 3019
 3020
 3021
 3022
 3023
 3024
 3025
 3026
 3027
 3028
